= ansible-tower config

Author: Prakhar Srivastava, psrivast@redhat.com and Shachar Boresntein, sha@redhat.com
Owner: Prakhar Srivastava, psrivast@redhat.com
Alternative Contacts: Tony Kay, tok@redhat.com,

== Overview

ansible-tower config was initially created for the babylon Project to deploy Ansible Tower and worker nodes (isolated nodes)


== Roles Included in `env_vars.yml`

. tower-copy-ssh

Role to copy ssh keys to connect to AWS instances from tower/worker nodes. The ssh public key needs to be available in all the AWS regions. Please use aws-cli or AWS console to copy the keys before you start running `dark-tower` scripts.

.. Variable needed

key_local_path: "~/.ssh/{{key_name}}.pem"

.. For example

key_local_path: "~/.ssh/ocpkey.pem"

. tower-license-injector

Role to setup Ansible Tower License. Set the tower licencse in the same format. Do not forget to add "eula_accepted: true", else the the process of setting us license will fail.

.. Variable Needed

# tower_license: >                   
#   {
#     "eula_accepted": true,
#     "company_name": "Red Hat",
#     "contact_email": "name@redhat.com",
#     "contact_name": "some person"
#     "hostname": "70a415ef832159a36413fa599",
#     "instance_count": 50,
#     "license_date": 16581423619,
#     "license_key":
#     "eea1b84d1e39cfEXAMPLE5739066069e60c6d0aEXAMPLE2c29cc61b2aEXAMPLE",
#     "license_type": "enterprise",
#     "subscription_name": "Ansible Tower by Red Hat (50 Managed Nodes), RHT Internal",
#     "trial": true
#   }

. cleanup-tower-default

Role to remove default(demo) project and inventories.

. tower-settings-update

Role to global tower settings:

.. Variable Needed

tower_setting_params:
  functionality1: "VALUE1"
  functionality2: "VALUE2"

.. For example

tower_setting_params:
  AWX_PROOT_BASE_PATH: "/tmp"
  AWX_PROOT_SHOW_PATHS: "'/var/lib/awx/projects/', '/tmp'"

. tower-pip-packages

Role to update python venv on tower/worker nodes.

# Path of Virtual Env for update
tower_update_venv: /var/lib/awx/venv/ansible

# Pip packages with version which needs to be updated for venv
pip_requirements: 
  - boto==2.49.0
  - boto3==1.9.200
  - awscli==1.16.210
  - ansible-tower-cli==3.3.6

. tower-user-create

Role to create tower users 

  - tower-org-create
  - tower-credential-create
  - tower-project-create
  - tower-inventory-create
  - tower-job-template-create
  - tower-babylon-job-runner


== Running Ansible Playbook



You can run the playbook with the following arguments to overwrite the default variable values:
From the `ansible_agnostic_deployer/ansible` directory run
`
[source,bash]
----
ansible-playbook ansible/main.yml  \
      -e @./ansible/configs/ans-tower-prod/sample_vars.yml \
      -e @../secret.yml \
      -e "guid=sborenstest2" -vvvv
----

=== To Delete an environment
----

REGION=us-east-1
KEYNAME=ocpkey
GUID=test02
ENVTYPE=ans-tower-lab
CLOUDPROVIDER=ec2

ansible-playbook configs/${ENVTYPE}/destroy_env.yml \
        -e "guid=${GUID}" -e "env_type=${ENVTYPE}" \
        -e "cloud_provider=${CLOUDPROVIDER}" \
        -e "aws_region=${REGION}"  -e "key_name=${KEYNAME}"  \
        -e "subdomain_base_suffix=${BASESUFFIX}" \
        -e @~/secret.yml -vv
----
